//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.09 at 02:26:09 PM MSK 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for player complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="player">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="coinCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="redDiamondCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="greenDiamondCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="blueDiamondCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "player", propOrder = {
    "login",
    "password",
    "lastLevel",
    "coinCount",
    "redDiamondCount",
    "greenDiamondCount",
    "blueDiamondCount"
})
public class Player {

    @XmlElement(required = true)
    protected String login;
    @XmlElement(required = true)
    protected String password;
    protected int lastLevel;
    protected int coinCount;
    protected int redDiamondCount;
    protected int greenDiamondCount;
    protected int blueDiamondCount;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the lastLevel property.
     * 
     */
    public int getLastLevel() {
        return lastLevel;
    }

    /**
     * Sets the value of the lastLevel property.
     * 
     */
    public void setLastLevel(int value) {
        this.lastLevel = value;
    }

    /**
     * Gets the value of the coinCount property.
     * 
     */
    public int getCoinCount() {
        return coinCount;
    }

    /**
     * Sets the value of the coinCount property.
     * 
     */
    public void setCoinCount(int value) {
        this.coinCount = value;
    }

    /**
     * Gets the value of the redDiamondCount property.
     * 
     */
    public int getRedDiamondCount() {
        return redDiamondCount;
    }

    /**
     * Sets the value of the redDiamondCount property.
     * 
     */
    public void setRedDiamondCount(int value) {
        this.redDiamondCount = value;
    }

    /**
     * Gets the value of the greenDiamondCount property.
     * 
     */
    public int getGreenDiamondCount() {
        return greenDiamondCount;
    }

    /**
     * Sets the value of the greenDiamondCount property.
     * 
     */
    public void setGreenDiamondCount(int value) {
        this.greenDiamondCount = value;
    }

    /**
     * Gets the value of the blueDiamondCount property.
     * 
     */
    public int getBlueDiamondCount() {
        return blueDiamondCount;
    }

    /**
     * Sets the value of the blueDiamondCount property.
     * 
     */
    public void setBlueDiamondCount(int value) {
        this.blueDiamondCount = value;
    }

}
